/**
 * 内置术语表（随扩展发布，只读）
 *
 * 术语表机制：popup 里勾选要启用的词库 → 勾中的条目合并进翻译请求的
 * glossary 参数 → 服务端构造进 prompt（"GLOSSARY (use these exact
 * translations)"）。未勾选的词库不参与翻译。
 *
 * 数据来源：公开网络术语资料整理（见各词库 source 字段）。
 * 条目为 [原文, 固定译法] 二元组；总量封顶见 background.js 的
 * GLOSSARY_MAX_ENTRIES（与服务端 build_translate_prompt 一致）。
 *
 * 本文件同时被 popup（<script>）和 background（importScripts）加载，
 * 因此必须挂在 globalThis 上。
 */
globalThis.BUILTIN_GLOSSARIES = [
  {
    id: 'finance',
    name: '金融财经',
    desc: '美联储、利率、债券、股市等财经新闻高频术语',
    source: '参考和讯网《股市术语的英文表达》(m.hexun.com/stock/2024-07-03/213405854.html)、wordln《经济新闻常用英语》《金融里的英文缩写简称》(wordln.com)、雅言翻译《300个常用经济金融专业术语》等公开资料整理',
    entries: [
      ['GDP', '国内生产总值'],
      ['CPI', '消费者价格指数'],
      ['PPI', '生产者价格指数'],
      ['PMI', '采购经理人指数'],
      ['Fed', '美联储'],
      ['Federal Reserve', '美联储'],
      ['interest rate', '利率'],
      ['rate cut', '降息'],
      ['rate hike', '加息'],
      ['monetary policy', '货币政策'],
      ['fiscal policy', '财政政策'],
      ['quantitative easing', '量化宽松'],
      ['quantitative tightening', '量化紧缩'],
      ['inflation', '通货膨胀'],
      ['deflation', '通货紧缩'],
      ['stagflation', '滞胀'],
      ['recession', '经济衰退'],
      ['depression', '经济萧条'],
      ['bull market', '牛市'],
      ['bear market', '熊市'],
      ['stock market', '股市'],
      ['index fund', '指数基金'],
      ['ETF', '交易所交易基金'],
      ['IPO', '首次公开募股'],
      ['yield', '收益率'],
      ['bond yield', '债券收益率'],
      ['Treasury bond', '美国国债'],
      ['yield curve', '收益率曲线'],
      ['inverted yield curve', '收益率曲线倒挂'],
      ['dividend', '股息'],
      ['dividend yield', '股息率'],
      ['market capitalization', '市值'],
      ['earnings per share', '每股收益'],
      ['P/E ratio', '市盈率'],
      ['revenue', '营收'],
      ['net income', '净利润'],
      ['profit margin', '利润率'],
      ['balance sheet', '资产负债表'],
      ['cash flow', '现金流'],
      ['merger and acquisition', '并购'],
      ['tariff', '关税'],
      ['subsidy', '补贴'],
      ['fiscal deficit', '财政赤字'],
      ['trade deficit', '贸易逆差'],
      ['trade surplus', '贸易顺差'],
      ['unemployment rate', '失业率'],
      ['hedge fund', '对冲基金'],
      ['short selling', '做空'],
      ['leverage', '杠杆'],
      ['volatility', '波动率'],
      ['central bank', '中央银行'],
      ['European Central Bank', '欧洲央行'],
      ['Bank of Japan', '日本央行'],
      ['People\'s Bank of China', '中国人民银行']
    ]
  },
  {
    id: 'tech',
    name: '科技互联网',
    desc: 'AI、云计算、网络安全、半导体等科技报道高频术语',
    source: '参考 wordln《科技文章中常用英语词汇》(wordln.com/article/8774278.html)、CSDN《软件设计师专业英语高频词汇速查手册》等公开资料整理',
    entries: [
      ['artificial intelligence', '人工智能'],
      ['machine learning', '机器学习'],
      ['deep learning', '深度学习'],
      ['neural network', '神经网络'],
      ['natural language processing', '自然语言处理'],
      ['large language model', '大语言模型'],
      ['generative AI', '生成式人工智能'],
      ['algorithm', '算法'],
      ['big data', '大数据'],
      ['cloud computing', '云计算'],
      ['cloud native', '云原生'],
      ['serverless', '无服务器计算'],
      ['microservices', '微服务'],
      ['containerization', '容器化'],
      ['blockchain', '区块链'],
      ['cryptocurrency', '加密货币'],
      ['bitcoin', '比特币'],
      ['internet of things', '物联网'],
      ['cybersecurity', '网络安全'],
      ['encryption', '加密'],
      ['authentication', '认证'],
      ['phishing', '网络钓鱼'],
      ['semiconductor', '半导体'],
      ['chip', '芯片'],
      ['quantum computing', '量子计算'],
      ['virtual reality', '虚拟现实'],
      ['augmented reality', '增强现实'],
      ['metaverse', '元宇宙'],
      ['digital transformation', '数字化转型'],
      ['chatbot', '聊天机器人'],
      ['recommendation system', '推荐系统'],
      ['computer vision', '计算机视觉'],
      ['edge computing', '边缘计算'],
      ['open source', '开源'],
      ['software as a service', '软件即服务'],
      ['platform as a service', '平台即服务'],
      ['infrastructure as a service', '基础设施即服务'],
      ['startup', '初创公司'],
      ['unicorn', '独角兽公司'],
      ['ecosystem', '生态系统'],
      ['user interface', '用户界面'],
      ['user experience', '用户体验'],
      ['data center', '数据中心'],
      ['bandwidth', '带宽'],
      ['firewall', '防火墙'],
      ['facial recognition', '人脸识别'],
      ['autonomous vehicle', '自动驾驶汽车']
    ]
  },
  {
    id: 'business',
    name: '商业新闻',
    desc: '财报、并购、公司治理、劳动力等商业报道高频表达',
    source: '综合公开财经新闻常用表达整理（wordln《经济新闻常用英语》等）',
    entries: [
      ['earnings', '财报'],
      ['quarterly earnings', '季度财报'],
      ['revenue growth', '营收增长'],
      ['gross margin', '毛利率'],
      ['operating margin', '营业利润率'],
      ['net profit', '净利润'],
      ['guidance', '业绩指引'],
      ['forecast', '预测'],
      ['analyst', '分析师'],
      ['upgrade', '上调评级'],
      ['downgrade', '下调评级'],
      ['board of directors', '董事会'],
      ['chief executive officer', '首席执行官'],
      ['chief financial officer', '首席财务官'],
      ['shareholder', '股东'],
      ['share buyback', '股票回购'],
      ['compensation', '薪酬'],
      ['corporate governance', '公司治理'],
      ['restructuring', '重组'],
      ['bankruptcy', '破产'],
      ['joint venture', '合资企业'],
      ['headquarters', '总部'],
      ['subsidiary', '子公司'],
      ['market share', '市场份额'],
      ['antitrust', '反垄断'],
      ['lawsuit', '诉讼'],
      ['settlement', '和解'],
      ['recall', '召回'],
      ['patent', '专利'],
      ['intellectual property', '知识产权'],
      ['workforce', '劳动力'],
      ['wage', '工资'],
      ['union', '工会'],
      ['strike', '罢工'],
      ['labor shortage', '劳动力短缺'],
      ['supply chain', '供应链'],
      ['layoffs', '裁员']
    ]
  }
];
